### ISSUE TITLE
Last modified section assumption

### ISSUE THREAD

**Issue by SHAESEN2** [thebioengineer/validation#6]
If you assume the developer follows GDP rules for writing the function section: "Last modified date", you can drop the dependency on lubricate and assume a character input.

**Comment by thebioengineer** [comment]
Thanks for the thoughts - from experience it is hard to always count on the correct date format, and I don't feel as though the lubridate dependency is very high. Additionally, by converting the values into Date values, we can also do comparisons across specs/test cases/test code dates that couldn't be done with characters.
